#!/usr/bin/env python3
"""Finalize ADRs at the end of a batch.

Performs three deterministic passes (no LLM):
  1. Promote: every docs/adr/NNNN-*.md with status:proposed and (optionally)
     matching --batch is flipped to status:accepted.
  2. Retroactive backfill: for every newly-promoted ADR with `supersedes: [...]`,
     open each predecessor and set frontmatter.superseded_by + frontmatter.status.
     This is the ONLY mutation allowed on an existing ADR's frontmatter; the
     body is never modified.
  3. Regenerate index.md: reads all ADR frontmatter, partitions by status,
     writes docs/adr/index.md.

Pure stdlib. Frontmatter parser handles a small YAML subset (key:value,
flow lists [a, b], strings, null) — enough for our ADR format.

Usage:
  finalize_adr.py [--decisions-dir docs/adr] [--batch <slug>] [--dry-run]

Exit:
  0  OK
  1  malformed ADR or write failure
"""
from __future__ import annotations
import sys
import re
import argparse
from pathlib import Path
from datetime import date


FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n?(.*)", re.DOTALL)
ADR_FILE_RE = re.compile(r"^(\d{4})-(.+)\.md$")


def parse_frontmatter(text: str):
    """Return (frontmatter_dict, body_text). dict preserves source order
    via insertion. None for missing frontmatter."""
    m = FRONTMATTER_RE.match(text)
    if not m:
        return None, text
    fm_text = m.group(1)
    body = m.group(2)
    fm: dict = {}
    for line in fm_text.split("\n"):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        k = k.strip()
        v = v.strip()
        if v.startswith("[") and v.endswith("]"):
            inner = v[1:-1].strip()
            if not inner:
                fm[k] = []
            else:
                items = [x.strip().strip("'\"") for x in inner.split(",")]
                fm[k] = items
        elif v.lower() == "null" or v == "":
            fm[k] = None
        else:
            fm[k] = v.strip("'\"")
    return fm, body


def serialize_frontmatter(fm: dict, body: str) -> str:
    lines = ["---"]
    for k, v in fm.items():
        if v is None:
            lines.append(f"{k}: null")
        elif isinstance(v, list):
            if not v:
                lines.append(f"{k}: []")
            else:
                lines.append(f"{k}: [{', '.join(str(x) for x in v)}]")
        elif isinstance(v, bool):
            lines.append(f"{k}: {'true' if v else 'false'}")
        else:
            lines.append(f"{k}: {v}")
    lines.append("---")
    if not body.startswith("\n"):
        lines.append("")
    return "\n".join(lines) + body


def adr_id_of(path: Path) -> str | None:
    m = ADR_FILE_RE.match(path.name)
    return m.group(1) if m else None


def title_of(path: Path) -> str:
    m = ADR_FILE_RE.match(path.name)
    if not m:
        return path.stem
    return m.group(2).replace("-", " ").title()


def load_adrs(dec_dir: Path):
    """Return dict: id → (path, fm, body). Skip files without frontmatter."""
    adrs = {}
    for f in sorted(dec_dir.glob("[0-9]*.md")):
        aid = adr_id_of(f)
        if not aid:
            continue
        fm, body = parse_frontmatter(f.read_text())
        if fm is None:
            print(f"WARN: {f} has no frontmatter, skipping", file=sys.stderr)
            continue
        adrs[aid] = (f, fm, body)
    return adrs


def regen_index(dec_dir: Path, adrs: dict):
    today = date.today().isoformat()
    out = [f"# ADR Index", "", f"_Auto-generated by `finalize_adr.py` on {today}._", ""]

    by_status: dict[str, list[tuple[str, Path, dict]]] = {
        "accepted": [],
        "proposed": [],
        "superseded": [],
        "deprecated": [],
    }
    for aid, (path, fm, _) in adrs.items():
        status = (fm.get("status") or "proposed").lower()
        by_status.setdefault(status, []).append((aid, path, fm))

    def fmt_entry(aid: str, path: Path, fm: dict) -> str:
        title = title_of(path)
        bits = []
        sup = fm.get("supersedes") or []
        if sup:
            bits.append(f"supersedes: {', '.join(str(x) for x in sup)}")
        sb = fm.get("superseded_by")
        if sb:
            bits.append(f"superseded by: {sb}")
        tags = fm.get("tags") or []
        if tags:
            bits.append(f"tags: [{', '.join(str(x) for x in tags)}]")
        suffix = " — " + " — ".join(bits) if bits else ""
        return f"- [{aid} — {title}](./{path.name}){suffix}"

    section_titles = [
        ("accepted",   "Active (accepted)"),
        ("proposed",   "Proposed (pending /finalize)"),
        ("superseded", "Superseded"),
        ("deprecated", "Deprecated"),
    ]

    for key, title in section_titles:
        items = sorted(by_status.get(key, []), key=lambda x: x[0])
        if not items:
            continue
        out.append(f"## {title}")
        out.append("")
        for aid, path, fm in items:
            out.append(fmt_entry(aid, path, fm))
        out.append("")

    # Topic chains: group accepted+superseded by tag, render chain
    chains: dict[str, list[str]] = {}
    for aid, (_, fm, _) in adrs.items():
        for tag in (fm.get("tags") or []):
            chains.setdefault(tag, []).append(aid)
    if chains:
        out.append("## Topic chains")
        out.append("")
        for tag in sorted(chains):
            ids = sorted(chains[tag])
            out.append(f"### {tag}")
            out.append("")
            out.append(" → ".join(ids))
            out.append("")

    (dec_dir / "index.md").write_text("\n".join(out))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--decisions-dir", default="docs/adr")
    ap.add_argument("--batch", default=None, help="restrict promotion to ADRs with this batch slug")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    dec_dir = Path(args.decisions_dir)
    if not dec_dir.is_dir():
        print(f"ERROR: directory not found: {dec_dir}", file=sys.stderr)
        sys.exit(1)

    adrs = load_adrs(dec_dir)
    if not adrs:
        print(f"INFO: no ADRs in {dec_dir}; regenerating empty index.md")
        if not args.dry_run:
            regen_index(dec_dir, adrs)
        sys.exit(0)

    promoted: list[str] = []
    superseded: list[str] = []
    errors: list[str] = []

    # Pass 1: promote
    for aid, (path, fm, body) in list(adrs.items()):
        if (fm.get("status") or "").lower() == "proposed":
            if args.batch is None or fm.get("batch") == args.batch:
                fm["status"] = "accepted"
                if not args.dry_run:
                    try:
                        path.write_text(serialize_frontmatter(fm, body))
                    except Exception as e:
                        errors.append(f"{path}: write failed: {e}")
                        continue
                promoted.append(aid)

    # Pass 2: retroactive supersedes backfill
    for new_id in promoted:
        new_fm = adrs[new_id][1]
        for old_raw in (new_fm.get("supersedes") or []):
            old_id = str(old_raw).strip().zfill(4)
            if old_id not in adrs:
                errors.append(f"{new_id}: supersedes references non-existent ADR {old_id}")
                continue
            old_path, old_fm, old_body = adrs[old_id]
            if (old_fm.get("status") or "").lower() != "superseded":
                old_fm["superseded_by"] = new_id
                old_fm["status"] = "superseded"
                if not args.dry_run:
                    try:
                        old_path.write_text(serialize_frontmatter(old_fm, old_body))
                    except Exception as e:
                        errors.append(f"{old_path}: write failed: {e}")
                        continue
                superseded.append(old_id)

    # Pass 3: regen index
    if not args.dry_run:
        # reload to get fresh state
        adrs = load_adrs(dec_dir)
        regen_index(dec_dir, adrs)

    summary = {
        "promoted": promoted,
        "retroactively_superseded": superseded,
        "errors": errors,
        "dry_run": args.dry_run,
    }
    import json
    print(json.dumps(summary, indent=2))
    sys.exit(0 if not errors else 1)


if __name__ == "__main__":
    main()
