#!/usr/bin/env python3
"""Regenerate CODEMAP.md (project root) by extracting module-level docstrings
from barrel files in the source tree.

Walks the source tree, identifies barrels by language convention, extracts
the first module-level docstring block via per-language regex, and writes
a flat CODEMAP.md. No LLM involvement; deterministic.

Default barrel patterns (used when no stack skill override):
  *.dart   barrel — .dart file containing top-level `library;`
  TS/JS    barrel — index.ts / index.js / index.tsx
  Python   barrel — __init__.py
  Rust     barrel — mod.rs / lib.rs
  Go       barrel — doc.go

Stack skill override: a stack skill MAY drop a `barrel_patterns.json` in
its directory listing patterns; this script reads it if present (best-effort,
not yet contracted — placeholder for next stage).

Usage:
  regen_codemap.py [--src-root .] [--out CODEMAP.md]

Exit:
  0 OK
  1 IO error
"""
from __future__ import annotations
import sys
import re
import argparse
from pathlib import Path


# (glob, regex with capture group 1 = raw docstring)
DEFAULT_BARRELS = [
    ("**/index.tsx", re.compile(r"^/\*\*([\s\S]*?)\*/", re.MULTILINE)),
    ("**/index.ts",  re.compile(r"^/\*\*([\s\S]*?)\*/", re.MULTILINE)),
    ("**/index.js",  re.compile(r"^/\*\*([\s\S]*?)\*/", re.MULTILINE)),
    ("**/__init__.py", re.compile(r'^"""([\s\S]*?)"""', re.MULTILINE)),
    ("**/mod.rs",    re.compile(r"^((?://!.*\n)+)", re.MULTILINE)),
    ("**/lib.rs",    re.compile(r"^((?://!.*\n)+)", re.MULTILINE)),
    ("**/doc.go",    re.compile(r"^((?://[^\n]*\n)+)", re.MULTILINE)),
]

# Dart needs a special filter — only files that contain `library;` are barrels.
DART_DOCSTRING_RE = re.compile(r"((?:^///[^\n]*\n)+)\s*library\s*;", re.MULTILINE)

EXCLUDE_DIR_PARTS = {
    "node_modules", ".git", "build", "dist", "target", ".dart_tool",
    "__pycache__", ".venv", "venv", ".next", ".nuxt", "coverage",
    "specs", "docs",  # these are harness-managed, not user code
}


def excluded(path: Path) -> bool:
    return any(part in EXCLUDE_DIR_PARTS for part in path.parts)


def clean_doc(raw: str) -> str:
    """Strip comment markers from extracted block."""
    cleaned = re.sub(r"^\s*(?:///|//!|//|\*|#)\s?", "", raw, flags=re.MULTILINE)
    return "\n".join(line.rstrip() for line in cleaned.split("\n")).strip()


def find_default_barrels(src_root: Path):
    """Yield (relative_path, docstring_or_None) for each barrel found."""
    for glob, regex in DEFAULT_BARRELS:
        for path in src_root.glob(glob):
            if excluded(path) or not path.is_file():
                continue
            try:
                text = path.read_text(errors="ignore")
            except Exception:
                continue
            m = regex.search(text)
            doc = clean_doc(m.group(1)) if m else None
            yield path.relative_to(src_root), doc

    # Dart: only files containing `library;`
    for path in src_root.glob("**/*.dart"):
        if excluded(path) or not path.is_file():
            continue
        try:
            text = path.read_text(errors="ignore")
        except Exception:
            continue
        m = DART_DOCSTRING_RE.search(text)
        if not m:
            # not a barrel (no `library;`) — skip
            continue
        doc = clean_doc(m.group(1))
        yield path.relative_to(src_root), doc


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src-root", default=".", help="source tree root (default: .)")
    ap.add_argument("--out", default="CODEMAP.md", help="output path")
    args = ap.parse_args()

    src_root = Path(args.src_root).resolve()
    out_path = Path(args.out)

    if not src_root.is_dir():
        print(f"ERROR: src-root not found: {src_root}", file=sys.stderr)
        sys.exit(1)

    entries = []
    seen = set()
    for rel_path, doc in find_default_barrels(src_root):
        key = str(rel_path)
        if key in seen:
            continue
        seen.add(key)
        entries.append((str(rel_path.parent), str(rel_path), doc or "_(no module docstring)_"))

    entries.sort()

    lines = [
        "# Codemap",
        "",
        f"_Auto-generated by `regen_codemap.py` from `{src_root}`._",
        f"_Modules: {len(entries)}_",
        "",
        "Each entry is a barrel file plus its module-level docstring (extracted from code; LLM not involved).",
        "Re-run `regen_codemap.py` after every batch via `/finalize`.",
        "",
        "---",
        "",
    ]

    if not entries:
        lines.append("_(no barrel files found — check that the source tree has language-conventional entry files)_")
    else:
        for module_dir, barrel_file, doc in entries:
            lines.append(f"## `{module_dir}/`")
            lines.append("")
            lines.append(f"_barrel:_ `{barrel_file}`")
            lines.append("")
            lines.append(doc)
            lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"OK: wrote {out_path} with {len(entries)} entries")


if __name__ == "__main__":
    main()
